#include <logger.hh>
#include <UnitTest++.h>
//
//
SUITE (LOGGER) {

 // ----------------------------------------------------
 TEST (print) {
  logger ("Message generated by unittest");
 }
}
// -----------------------------------------------------
